version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: apipass
      POSTGRES_USER: apiuser
      POSTGRES_DB: tgapi
    volumes:
      - postgre-api-data:/var/lib/postgresql/data
    networks:
      - app-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - app-net

  api-svc:
    image: api-svc
    container_name: api-svc
    hostname: api-svc
    build: 
      context: ../tag-and-trac-assessment-api
    ports:
      - 8080:8080
    networks:
      - app-net
    restart: on-failure


networks:
  app-net:
    
volumes:
  postgre-api-data:
    